# Form implementation generated from reading ui file 'qtdesigner/mainwin.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindowRoot(object):
    def setupUi(self, MainWindowRoot):
        MainWindowRoot.setObjectName("MainWindowRoot")
        MainWindowRoot.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindowRoot)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.histogram = HistogramView(self.centralwidget)
        self.histogram.setObjectName("histogram")
        self.horizontalLayout.addWidget(self.histogram)
        MainWindowRoot.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowRoot)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        MainWindowRoot.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowRoot)
        self.statusbar.setObjectName("statusbar")
        MainWindowRoot.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowRoot)
        QtCore.QMetaObject.connectSlotsByName(MainWindowRoot)

    def retranslateUi(self, MainWindowRoot):
        _translate = QtCore.QCoreApplication.translate
        MainWindowRoot.setWindowTitle(_translate("MainWindowRoot", "Histo Test"))
from pyqt_histogram.gui.histogramview import HistogramView
